name: "Build for Linux"

on:
    push:
    pull_request:
jobs:
    build-for-linux:
        name: Build

        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Install Node"
              uses: actions/setup-node@v3

            - name: Install deps and build
              uses: GabrielBB/xvfb-action@v1
              with:
                  run: |
                      npm i
                      npm run react-build
                      npm run linux-electron-build

            - uses: actions/upload-artifact@v3
              name: Upload deb build
              with:
                  name: "SE3-Launcher-linux-deb"
                  path: |
                      dist/*.deb

            - uses: actions/upload-artifact@v3
              name: Upload rpm build
              with:
                  name: "SE3-Launcher-linux-rpm"
                  path: |
                      dist/*.rpm

            - uses: actions/upload-artifact@v3
              name: Upload tar.gz build
              with:
                  name: "SE3-Launcher-linux-tar.gz"
                  path: |
                      dist/*.tar.gz

            - uses: actions/upload-artifact@v3
              name: Upload AppImage build
              with:
                  name: "SE3-Launcher-linux-AppImage"
                  path: |
                      dist/*.AppImage
