name: "Test on Linux"

on:
    push:
    pull_request:
jobs:
    test-on-linux:
        name: Test

        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Install Node"
              uses: actions/setup-node@v3

            - name: Install deps and test
              uses: GabrielBB/xvfb-action@v1
              with:
                  run: |
                      npm i
                      npm test
